# datum generated test cases
#
# do not modify this file directly as it is autogenerated and your changes
# will be lost
#
# source $$source_file$$
#

class $$class_name$$ < ActiveSupport::TestCase

  $$source_method$$

  $$test_cases$$

end